spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/resource_booking
spring.datasource.username=root

jwt.secret=DevSecretKeyForResourceBookingApplication123456789
jwt.expiration=3600000
jwt.issuer=resource-booking-api
jwt.audience=resource-booking-client

seed.admin.username=admin
seed.admin.password=admin

seed.user.username=user
seed.user.password=password

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true