spring.application.name=resource-booking

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/resource_booking}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8081}

logging.level.org.springframework.security=INFO

jwt.secret=${JWT_SECRET:DevSecretKeyForResourceBookingApplication123456789}
jwt.expiration=${JWT_EXPIRATION:3600000}


jwt.issuer=resource-booking-api
jwt.audience=resource-booking-client

seed.admin.username=${ADMIN_USERNAME}
seed.admin.password=${ADMIN_PASSWORD}

seed.user.username=${USER_USERNAME}
seed.user.password=${USER_PASSWORD}

springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}